-- StudyVault single-password online uploader
-- Run in Supabase SQL Editor.
-- Then deploy the Edge Function in supabase/functions/add-resource.
-- IMPORTANT: service role key stays ONLY in the Edge Function secret.

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  subject_id text not null,
  resource_type text not null,
  title text not null,
  url text not null,
  meta text default '',
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;

revoke all on public.resources from anon, authenticated;
grant select on public.resources to anon, authenticated;

drop policy if exists "public can read resources" on public.resources;
create policy "public can read resources"
on public.resources for select
to anon, authenticated
using (true);
